import { createCategory, getChildren, getRoots, getDescendants, formatCategoryPath } from './core/category-tree.js';
import { addCategory, deleteCategory, renameCategory } from './state/category-actions.js';
import { createTimeEntry } from './core/time-entry.js';
import { createActiveTimer, elapsedSeconds, elapsedMinutes } from './core/timer.js';
import { today, splitEntryByDay, addDays } from './core/time.js';
import { buildExportPayload, parseImportPayload } from './core/import-export.js';
import { renderCharts, destroyCharts } from './charts/dashboard.js';
import { clearAllData } from './core/storage.js';
import { DEFAULT_CATEGORIES } from './core/model.js';

export function createUI({ root, state, persist }) {
  let ticker;
  const rerender = () => render();
  function render() { destroyCharts(); root.replaceChildren(header()); const main=node('main','content'); main.append(state.tab==='entry'?entryPage():state.tab==='dashboard'?dashboardPage():categoriesPage()); root.appendChild(main); if(state.modal) root.appendChild(modal()); if(state.error) root.appendChild(node('div','error',state.error)); if(state.activeTimer){clearInterval(ticker);ticker=setInterval(()=>{const c=root.querySelector('[data-timer-clock]');if(c)c.textContent=clock(elapsedSeconds(state.activeTimer));},1000);}else clearInterval(ticker); if(state.tab==='dashboard')requestAnimationFrame(drawCharts); }
  function header(){const h=node('header','app-header');h.appendChild(node('h1','lt-title','Carnet du temps'));const nav=node('nav','tabs');[['entry','Saisie'],['dashboard','Tableau de bord'],['categories','Catégories']].forEach(([id,label])=>{const b=button(label,state.tab===id?'active':'secondary');b.classList.add('tab-btn');b.onclick=()=>{state.tab=id;state.modal=null;state.editingEntryId=null;state.error=null;rerender();};nav.appendChild(b);});h.appendChild(nav);return h;}
  function entryPage(){const f=document.createDocumentFragment();f.append(timerCard(),entryCard(),activitiesCard(),entriesCard(),dataCard());return f;}
  function timerCard(){const c=card('Timer');if(!state.activeTimer){c.appendChild(node('p','muted','Aucun timer actif.'));return c;}const t=state.activeTimer;const box=node('div','timer-active');box.append(node('div','muted',`${t.activity} · ${categoryPath(t.categoryId??t.cat)}`),node('div','t-clock',clock(elapsedSeconds(t))));box.lastChild.dataset.timerClock='1';const stop=button('Arrêter le timer','danger');stop.onclick=stopTimer;box.appendChild(stop);c.appendChild(box);return c;}
  function entryCard(){const c=card(state.editingEntryId?'Modifier une entrée':'Nouvelle entrée');const old=state.entries.find(e=>e.id===state.editingEntryId);const form=node('form','entry-form');const activity=input('Activité','text',old?.activity||'',true),category=selectCategory(old?.categoryId);attachActivitySuggestions(activity,category);const date=input('Date','date',old?.date||today(),true),start=input('Début','time',old?.start||'09:00',true),end=input('Fin','time',old?.end||'10:00',true);const row=node('div','row');row.append(date.wrap,start.wrap,end.wrap);form.append(activity.wrap,category.wrap,row);const save=button(old?'Enregistrer les modifications':'Enregistrer');save.type='submit';form.appendChild(save);const timer=button('Démarrer le timer','secondary');timer.onclick=()=>startTimer(activity.input.value.trim(),category.select.value,date.input.value,start.input.value);form.appendChild(timer);if(old){const cancel=button('Annuler','secondary');cancel.onclick=()=>{state.editingEntryId=null;rerender();};form.appendChild(cancel);}form.onsubmit=async e=>{e.preventDefault();const value=createTimeEntry({id:old?.id||crypto.randomUUID(),activity:activity.input.value,categoryId:category.select.value||null,date:date.input.value,start:start.input.value,end:end.input.value});if(!value.activity||value.mins<=0){showError(c,'Vérifiez l’activité et les horaires.');return;}state.entries=old?state.entries.map(x=>x.id===old.id?value:x):[value,...state.entries];state.editingEntryId=null;state.error=null;await persist();rerender();};c.appendChild(form);return c;}
  function attachActivitySuggestions(activity,category){const listId=`activity-suggestions-${crypto.randomUUID()}`;const list=document.createElement('datalist');list.id=listId;activity.input.setAttribute('list',listId);activity.wrap.appendChild(list);const refresh=()=>{const selectedId=category.select.value;list.replaceChildren();if(!selectedId)return;const allowed=new Set([selectedId,...getDescendants(state.categories,selectedId).map(x=>x.id)]);const seen=new Set();for(const a of state.activities){const name=String(a.label||a.name||a.activity||'').trim();const categoryId=a.categoryId??a.cat;if(!name||!categoryId||!allowed.has(categoryId)||seen.has(name.toLowerCase()))continue;const option=document.createElement('option');option.value=name;list.appendChild(option);seen.add(name.toLowerCase());}};category.select.addEventListener('change',refresh);refresh();}
  function activitiesCard(){const c=card('Activités enregistrées');const add=button('Ajouter une activité','secondary');add.onclick=()=>{state.modal={type:'activity'};state.error=null;rerender();};c.appendChild(add);for(const a of state.activities){const r=node('div','entry-row');r.appendChild(node('div',null,`${a.label||a.activity||''} · ${categoryPath(a.categoryId)}`));const go=button('Démarrer','small');go.onclick=()=>startTimer(a.label||a.activity,a.categoryId,today(),nowTime());const del=button('×','small danger');del.onclick=async()=>{state.activities=state.activities.filter(x=>x.id!==a.id);await persist();rerender();};r.append(go,del);c.appendChild(r);}return c;}
  function entriesCard(){const c=card('Dernières entrées');if(!state.entries.length)c.appendChild(node('p','empty','Aucune entrée.'));for(const e of state.entries.slice(0,15)){const r=node('div','entry-row');const info=node('div');info.append(node('strong',null,e.activity),node('div','entry-meta',`${e.date} · ${e.start}–${e.end} · ${Math.round(e.mins)} min · ${categoryPath(e.categoryId)}`));const edit=button('Modifier','small');edit.onclick=()=>{state.editingEntryId=e.id;rerender();};const del=button('Supprimer','small danger');del.onclick=async()=>{state.entries=state.entries.filter(x=>x.id!==e.id);await persist();rerender();};r.append(info,edit,del);c.appendChild(r);}return c;}
  function dashboardPage(){const f=document.createDocumentFragment(),periods=node('div','period-tabs');for(const p of ['7','14','30','90']){const b=button(`${p} jours`,state.period===p?'active':'secondary');b.onclick=()=>{state.period=p;rerender();};periods.appendChild(b);}f.appendChild(periods);const data=dashboardEntries(),total=data.reduce((s,e)=>s+e.mins,0),metrics=node('div','metric-grid');metrics.append(metric('Temps total',`${Math.floor(total/60)}h ${Math.round(total%60)}m`),metric('Entrées',data.length),metric('Jours actifs',new Set(data.map(e=>e.date)).size));f.appendChild(metrics);const chart=card('Statistiques');chart.append(node('h3','chart-title','Temps par jour'));const dc=document.createElement('canvas');dc.id='day-chart';chart.appendChild(dc);chart.append(node('h3','chart-title','Répartition par heure'));const hc=document.createElement('canvas');hc.id='hour-chart';chart.appendChild(hc);chart.append(node('h3','chart-title','Répartition du temps par catégorie / sous-catégorie'));const cc=document.createElement('canvas');cc.id='category-chart';chart.appendChild(cc);f.appendChild(chart);return f;}
  function categoriesPage(){const f=document.createDocumentFragment(),c=card('Arbre des catégories');const add=button('Nouvelle catégorie racine');add.onclick=()=>{state.modal={type:'category',parentId:null};rerender();};c.appendChild(add);const tree=node('div','category-tree');for(const rootCat of getRoots(state.categories))tree.appendChild(categoryNode(rootCat));c.appendChild(tree);f.appendChild(c);return f;}
  function categoryNode(c){const wrap=node('div','category-node'),head=node('div','category-head');head.append(node('strong',null,c.label),node('span','muted',categoryPath(c.id)));wrap.appendChild(head);const actions=node('div','category-actions');const child=button('Sous-catégorie','small');child.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();state.modal={type:'category',parentId:c.id};state.error=null;rerender();});const rename=button('Renommer','small');rename.onclick=e=>{e.preventDefault();e.stopPropagation();state.modal={type:'rename',id:c.id};state.error=null;rerender();};const del=button('Supprimer','small danger');del.disabled=c.builtin;del.onclick=e=>{e.preventDefault();e.stopPropagation();removeCategory(c.id);};actions.append(child,rename,del);wrap.appendChild(actions);const children=node('div','category-children');for(const childCat of getChildren(state.categories,c.id))children.appendChild(categoryNode(childCat));wrap.appendChild(children);return wrap;}
  async function removeCategory(id){const ids=new Set([id,...getDescendants(state.categories,id).map(x=>x.id)]);state.categories=deleteCategory(state.categories,id,{cascade:true});state.entries=state.entries.map(e=>ids.has(e.categoryId)?{...e,categoryId:null}:e);state.activities=state.activities.map(a=>ids.has(a.categoryId)?{...a,categoryId:null}:a);await persist();rerender();}
  function modal(){const m=state.modal;const overlay=node('div','modal-overlay');overlay.addEventListener('click',e=>{if(e.target===overlay){state.modal=null;rerender();}});const box=node('div','modal-box');const head=node('div','modal-head');const titleText=m.type==='activity'?'Activité enregistrée':m.type==='rename'?'Renommer la catégorie':m.parentId?'Nouvelle sous-catégorie':'Nouvelle catégorie';const title=node('h2','card-title',titleText),close=button('×','modal-close');close.onclick=()=>{state.modal=null;rerender();};head.append(title,close);box.appendChild(head);const form=node('form');if(m.type==='activity'){const a=input('Nom','text','',true),c=selectCategory(state.categories[0]?.id);const save=button('Enregistrer');save.type='submit';form.append(a.wrap,c.wrap,save);form.onsubmit=async e=>{e.preventDefault();const label=a.input.value.trim();if(!label)return;state.activities.push({id:crypto.randomUUID(),label,categoryId:c.select.value});state.modal=null;await persist();rerender();};}else{const old=m.type==='rename'?state.categories.find(x=>x.id===m.id):null,name=input('Nom','text',old?.label||'',true),color=input('Couleur','color',old?.color||'#5C7A5E',false),save=button(old?'Renommer':'Créer');save.type='submit';form.append(name.wrap,color.wrap,save);form.onsubmit=async e=>{e.preventDefault();const label=name.input.value.trim();if(!label)return;try{if(old)state.categories=renameCategory(state.categories,m.id,label);else state.categories=addCategory(state.categories,{...createCategory({id:uniqueId(label),label,color:color.input.value,parentId:m.parentId}),builtin:false});state.modal=null;await persist();rerender();}catch(err){showError(box,err.message);}};}box.appendChild(form);overlay.appendChild(box);return overlay;}
  function dataCard(){const c=card('Données'),row=node('div','action-row'),exp=button('Exporter'),imp=button('Importer'),clear=button('Effacer toutes les données','danger');exp.onclick=exportData;imp.onclick=()=>{const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.onchange=()=>importData(file);file.click();};clear.onclick=clearData;row.append(exp,imp,clear);c.appendChild(row);return c;}
  function exportData(){const payload=buildExportPayload({entries:state.entries,savedActivities:state.activities,categories:state.categories});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`time-tracker-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);}
  async function importData(input){const file=input.files?.[0];if(!file)return;state.error=null;try{const data=parseImportPayload(await file.text());const builtins=state.categories.filter(c=>c.builtin),ids=new Set(builtins.map(c=>c.id));state.entries=data.entries;state.activities=data.savedActivities;state.categories=[...builtins,...data.categories.filter(c=>!ids.has(c.id))];await persist();rerender();}catch(e){state.error=e?.message||'Impossible d’importer ce fichier JSON.';rerender();}}
  async function clearData(){if(!window.confirm('Effacer toutes les données locales ? Cette action est irréversible.'))return;try{await clearAllData();state.entries=[];state.activities=[];state.categories=DEFAULT_CATEGORIES.map(c=>({...c}));state.activeTimer=null;state.modal=null;state.editingEntryId=null;state.error=null;state.tab='entry';await persist();rerender();}catch(e){state.error=e?.message||'Impossible d’effacer toutes les données.';rerender();}}
  async function startTimer(activity,categoryId,date,startTime){if(!activity||!categoryId)return;state.activeTimer=createActiveTimer({activity,categoryId,startTs:Date.now(),startTime,date});await persist();rerender();}
  async function stopTimer(){const t=state.activeTimer;if(!t)return;const end=nowTime(),endDate=t.date===today()?t.date:today();const entry=createTimeEntry({id:crypto.randomUUID(),activity:t.activity,categoryId:t.categoryId??t.cat,date:t.date,start:t.startTime,end,endDate,mins:elapsedMinutes(t)});state.entries=[entry,...state.entries];state.activeTimer=null;await persist();rerender();}
  function dashboardEntries(){const end=new Date(),days=Number(state.period)||7,start=new Date(end);start.setDate(start.getDate()-days+1);const min=start.toISOString().slice(0,10),max=end.toISOString().slice(0,10);return state.entries.flatMap(splitEntryByDay).filter(e=>e.date>=min&&e.date<=max);}
  function drawCharts(){const d=root.querySelector('#day-chart'),h=root.querySelector('#hour-chart'),c=root.querySelector('#category-chart');if(d&&h)renderCharts({dayCanvas:d,hourCanvas:h,categoryCanvas:c,entries:dashboardEntries()});}
  function selectCategory(selected){const wrap=node('div','field');wrap.appendChild(label('Catégorie'));const select=document.createElement('select');for(const c of state.categories){const o=document.createElement('option');o.value=c.id;o.textContent=formatCategoryPath(state.categories,c.id);o.selected=c.id===selected;select.appendChild(o);}wrap.appendChild(select);return {wrap,select};}
  function input(labelText,type,value,required){const wrap=node('div','field');wrap.appendChild(label(labelText));const input=document.createElement('input');input.type=type;input.value=value??'';input.required=required;wrap.appendChild(input);return {wrap,input};}
  function categoryPath(id){return id?formatCategoryPath(state.categories,id):'Sans catégorie';}
  function uniqueId(text){const base=text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'category';let id=base,n=2;while(state.categories.some(c=>c.id===id))id=`${base}-${n++}`;return id;}
  function metric(labelText,value){return node('div','metric',`${labelText}: ${value}`);}
  function card(title){const c=node('section','card');c.appendChild(node('h2','card-title',title));return c;}
  function button(text,kind=''){const b=document.createElement('button');b.type='button';b.className=`btn ${kind}`;b.textContent=text;return b;}
  function label(text){return node('label',null,text);}
  function node(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=String(text);return n;}
  function showError(parent,message){const old=parent.querySelector('.error');old?.remove();parent.prepend(node('div','error',message));}
  function nowTime(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
  function clock(s){return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
  render();
  return { render, destroy:()=>{clearInterval(ticker);destroyCharts();} };
}